format_version: v1.0
type: UniqueComponent
attributes: {id: a_classd}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: tr}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
- type: ElementPosition
  attributes: {x: '54', y: '102', id: a_classd}
